---

- name: Install python software
  apt:
    name: python-software-properties
    state: present


- name: Add apt key for nodesource
  apt_key: 
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key


- name: Add NodeSource repositories for Node.js
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
  register: node_repo


- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo.changed


- name: Install nodejs
  apt:
    name: nodejs
    state: present